import re
import json


class Parser:
    """
    parser class
    parse the answer from the response generated by the model
    """

    def __init__(self, task: str):
        # task in ['gameof24','checkmate','wordsorting']
        self.task = task

    def parse(self, response: str) -> str:
        """
        parse the answer from the response
        """
        if "gameof24" in self.task:
            return self._parse_gameof24(response)
        elif "checkmate" in self.task:
            return self._parse_checkmate(response)
        elif "wordsorting" in self.task:
            return self._parse_wordsorting(response)
        else:
            return response

    def _parse_gameof24(self, response: str) -> str:
        """
        parse the answer from the response of the gameof24 task

        the format of the ruled answer is:

        "Final Answer: "
        """

        prioritized_response = response.split("\n")[-1]
        priotitized_pattern = [
            r"Final Answer: (.*)",
            r"Answer: (.*)",
            r"Final answer: (.*)",
            r"final answer: (.*)",
        ]
        for pattern in priotitized_pattern:
            match = re.search(pattern, prioritized_response)
            if match:
                return match.group(1)
        return prioritized_response

    def _parse_checkmate(self, response: str) -> str:
        pass

    def _parse_wordsorting(self, response: str) -> str:
        pass


# parser = Parser("gameof24")

# i = 0
# with open("test.jsonl") as f:
#     for line in f:
#         response = json.loads(line)["output"]
#         print(i)
#         print(parser.parse(response))
#         i += 1
